image: node:22.13.1-slim

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - ./build_all.sh

deploy_job:
  image: ruby:3.2.1
  stage: deploy
  script:
    - curl $DEPLOY_URL
  only:
    - deploy